### ISSUE TITLE
Investigate chest related crashes

### ISSUE THREAD

**Issue by richardhendricks** [richardhendricks/GT5-Unofficial#3]
[04:32:03] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 11/20/17 4:32 AM
Description: Ticking memory connection

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at net.minecraftforge.common.ChestGenHooks.generateStacks(ChestGenHooks.java:111)
	at net.minecraft.util.WeightedRandomChestContent.generateChestContent(WeightedRandomChestContent.java:93)
	at net.minecraft.util.WeightedRandomChestContent.func_76293_a(WeightedRandomChestContent.java:38)
	at net.minecraft.world.gen.structure.StructureComponent.func_74879_a(StructureComponent.java:744)
	at net.minecraft.world.gen.structure.StructureVillagePieces$House2.func_74875_a(StructureVillagePieces.java:934)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:44)
	at net.minecraft.world.gen.structure.MapGenStructure.func_75051_a(MapGenStructure.java:93)
	at rwg.world.ChunkGeneratorRealistic.func_73153_a(ChunkGeneratorRealistic.java:496)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:370)
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:97)
	at net.minecraft.server.management.PlayerManager.func_72691_b(PlayerManager.java:174)
	at net.minecraft.server.management.PlayerManager.func_72685_d(PlayerManager.java:267)
	at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:313)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:404)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Happens with world seed = -1, travel due south ~1500 blocks, should hit it.

**Comment by richardhendricks** [comment]
Root caused to minimum number being larger than maximum.  nextInt requires a positive number. Issue filed with primary mod.
